[mypy]
warn_unused_configs = True
ignore_missing_imports = True


exclude = (?x)(
    ^source/stockplanconnect.py$    
    ^source/stockplanconnect/_version.py$
    ^amazon_invoice_sanitize.py$
    ^source/schwab_csv.py$
  
    ^source/ofx.py$
    ^source/amazon_invoice.py$
    ^source/__init__.py$
    ^training.py$
  )
[mypy-beancount_import/source/stockplanconnect.*]
ignore_errors = True
[mypy-beancount_import/source/amazon_invoice_sanitize.*]
ignore_errors = True
[mypy-beancount_import/source/amazon_invoice.*]
ignore_errors = True
[mypy-beancount_import/source/schwab_csv.*]
ignore_errors = True
[mypy-beancount_import/source/ofx.*]
ignore_errors = True

